services:
  postgres:
    image: postgis/postgis:13-3.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # persist postgres db 
      - postgres-data:/var/lib/postgresql/data
      # for access to datasets
      # requires read access for other
      # sudo chmod -R 777 /home/USERNAME/practicalsql/datasets
      - ./datasets:/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: False
    ports:
      - "8180:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
